### ISSUE TITLE
parser.h parseTXT function issues

### ISSUE THREAD

**Issue by codythegreat** [codythegreat/dss#2]
Currently I'm trying to port over the code that handles reading the text file in main.c over to another file parser.c to make it easier to maintain. I'm having a few issues implementing this:

My main issue is conceptualizing and implementing how the array of slides (currently of type char[][]) can be efficiently passed to and from parser.h. 

I'd like to do this efficiently without having to copy and reassign the array to new memory addresses.

**Comment by amagura** [comment]
What if you initialized the `slides` array in main.c and then passed it to the main function in parser.c by reference--by memory address--allowing the parser to act on it and have those changes reflected in the main program?

**Comment by codythegreat** [comment]
@amagura I'm currently considering holding each slide in a struct (so it'll be easier to add features and pass the struct in and out of functions later on. As an example: slide.number, slide.rgb) and these struct variables will be placed in an array. I've started laying the groundwork for this in parser.c. I'm not sure if that should be the file that the struct definition goes in however.

**Comment by codythegreat** [comment]
@amagura I'm trying to conceptualize in my head how we could keep track of each struct variable, so say I have `struct Slide` I would have an array to call where each index is a Slide. That way during the program loop if a user wanted to jump to the seventh slide we could call it in a similar manner to `structArray[6].content`

This is an over simplification and I'm not sure if this is best practice/memory safe in C as I'm still learning. If you have another suggestion that is better I'm all ears.

**Comment by codythegreat** [comment]
commit `2df1cdc` has moved all of the logic for parsing the txt files over to parser.c. I'll now close this issue.
