### ISSUE TITLE
Underline characters not displaying properly through SSH

### ISSUE THREAD

**Issue by codythegreat** [codythegreat/dss#4]
This issue is currently only occurring on my work computer through an SSH terminal to a remote server. Underline characters are either not fully being concatenated to each slide, or they're not being printed properly on the call to `printw` during the program loop. 

I'm not sure if this an environment issue for my ssh server but i have yet to reproduce this issue on my home Linux machine.

**Comment by amagura** [comment]
> Underline characters are either not fully being concatenated to each slide, or they're not being printed properly on the call to `printw` during the program loop.

By underline characters, do you mean characters that are underlined or `_` characters?

**Comment by codythegreat** [comment]
@amagura underscores. Currently for each sequence of underscores on a line I'm only seeing one underscore printed.
For instance `___text_____` would print `_text_`. I'm not seeing this behavior for any other characters.

**Comment by codythegreat** [comment]
This seems to be resolved now (at least on my ssh client/host)
