### ISSUE TITLE
Add in ability to jump to n slide, or jump to first/last slide

### ISSUE THREAD

**Issue by codythegreat** [codythegreat/dss#6]
### Enhancement
The following enhancements are planned for DSS:
+ `gg` - jump to first slide
+ `G` - jump to last slide
+ `ngg` / `nG` - jump to n slide

**Comment by amagura** [comment]
Adding <kbd>Space</kbd> as a shortcut to <kbd>j</kbd> would also be nice.

**Comment by codythegreat** [comment]
@amagura I just commited a pretty big update for the display/keyinput logic. I added your idea for the `space` key. `g` and `G` now move to first/last slide. More changes to come, but I think this will be a good foundation for us to expand.

**Comment by codythegreat** [comment]
This issue can be closed as all features have been implemented as of commit 93c071b
